# Generated by Django 3.2.9 on 2022-01-13 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='email',
            field=models.EmailField(default='abc@123.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='mobilenumber',
            field=models.IntegerField(),
        ),
    ]
