# Generated by Django 4.0.2 on 2022-02-16 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('studingin', models.CharField(max_length=10)),
                ('bloodgroup', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RegisterPrincipal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('password1', models.CharField(max_length=100)),
            ],
        ),
    ]
