# Generated by Django 4.0.2 on 2022-02-16 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='studingin',
            new_name='studing',
        ),
    ]
