# Generated by Django 3.2.9 on 2022-01-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cabin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('mob', models.IntegerField()),
                ('start', models.CharField(max_length=1000)),
                ('end', models.CharField(max_length=1000)),
                ('total', models.CharField(max_length=1000)),
            ],
        ),
    ]
