# Generated by Django 3.2.9 on 2022-01-24 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cabin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cabin',
            name='mob',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cabin',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
